version: 2

jobs:
  py36:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python3 odinair_libs/test_compile.py
            flake8 --exclude venv --max-line-length 120 --show-source --statistics --ignore F401

  py35:
    docker:
      - image: circleci/python:3.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python3 odinair_libs/test_compile.py
            flake8 --exclude venv --max-line-length 120 --show-source --statistics --ignore F401

workflows:
  version: 2
  build:
    jobs:
      - py35
      - py36