version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
            ./odinair_libs/scripts/test.sh

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements-dev.txt" }}
