version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - venv-dependencies

      # Installing Red as a dependency here could be useless,
      # but it's probably better to play it safe
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --process-dependency-links -U git+https://github.com/Cog-Creators/Red-DiscordBot@V3/develop
            pip install pycodestyle

      - save_cache:
          paths:
            - ./venv
          key: venv-dependencies

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m compileall ./
            pycodestyle --show-source --statistics --max-line-length=120 --exclude venv */
