version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python3 odinair_libs/test_compile.py
            flake8 --exclude venv --max-line-length 120 --show-source --statistics
