version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            pip install pycodestyle --user
            python _tests/compile.py
            pycodestyle --show-source --statistics --max-line-length=120 --exclude venv */
