version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pycodestyle
            python attempt_compile.py
            pycodestyle --show-source --statistics --max-line-length=120 --exclude venv */
