version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - venv-dependencies

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pycodestyle

      - save_cache:
          paths:
            - ./venv
          key: venv-dependencies

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python attempt_compile.py
            pycodestyle --show-source --statistics --max-line-length=120 --exclude venv */
